# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KE5qD9iUB-rddqZrxBl7s3KaUw69A5Dv
"""

# prompt: import pandas as pd
# df = pd.read_csv("/content/data.tsv", delimiter='\t', encoding='latin-1')
# df.head()
# rows=df.shape[0]
# cols=df.shape[1]
# print(" Number of Rows:",rows)
# print("Number ofColumns:",cols)
# file_path="/content/data.tsv"
# def count_lines(file_path):
#   with open(file_path,"r",errors="ignore") as file:
#     lines=file.readlines()
#     return len(lines)
# line_count=count_lines(file_path)
# pri

import pandas as pd
df = pd.read_csv("/content/data.tsv", delimiter='\t', encoding='latin-1')
df.head()
rows=df.shape[0]
cols=df.shape[1]
print(" Number of Rows:",rows)
print("Number ofColumns:",cols)
file_path="/content/data.tsv"
def count_lines(file_path):
  with open(file_path,"r",errors="ignore") as file:
    lines=file.readlines()
    return len(lines)
line_count=count_lines(file_path)
print("Line Count:",line_count)